language: node_js
node_js:
  - node
cache: yarn
jobs:
  include:
    - stage: unit test
      script: yarn test
    - stage: npm release
      script: yarn
      deploy:
        provider: npm
        email: "max@bionic-app.com"
        api_key: $NPM_TOKEN
        on: master