language: node_js
node_js:
  - node
cache: yarn
jobs:
  include:
    - stage: unit test
      script: yarn test
    - stage: npm release
      before_install:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      script: npm publish
      branches:
        only:
          - master