language: node_js
node_js:
  - node
cache: yarn
jobs:
  include:
    - stage: unit test
      script: yarn test
    - stage: npm release
      script: echo "deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        on: master